# Generated by Django 4.1.2 on 2022-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Backend",
                "verbose_name_plural": "Backend",
            },
        ),
        migrations.CreateModel(
            name="English",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "English",
                "verbose_name_plural": "English",
            },
        ),
        migrations.CreateModel(
            name="Frontend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Frontend",
                "verbose_name_plural": "Frontend",
            },
        ),
        migrations.CreateModel(
            name="FullStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Full_Stack",
                "verbose_name_plural": "Full_Stack",
            },
        ),
        migrations.CreateModel(
            name="GrafikDizayin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Grafik_dizayin",
                "verbose_name_plural": "Grafik_dizayin",
            },
        ),
        migrations.CreateModel(
            name="MobilIlova",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Mobil_ilova",
                "verbose_name_plural": "Mobil_ilova",
            },
        ),
        migrations.CreateModel(
            name="Robototexnika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Robototexnika",
                "verbose_name_plural": "Robototexnika",
            },
        ),
        migrations.CreateModel(
            name="Savodxonlik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Savodxonlik",
                "verbose_name_plural": "Savodxonlik",
            },
        ),
        migrations.CreateModel(
            name="SMM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "SMM",
                "verbose_name_plural": "SMM",
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UchDdizayin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.CharField(max_length=250)),
                ("time", models.CharField(max_length=300)),
                ("language", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "UchD_dizayin",
                "verbose_name_plural": "UchD_dizayin",
            },
        ),
    ]
