# Generated by Django 4.1.2 on 2022-10-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListOfStudents",
            fields=[
                (
                    "students_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="db_users.students",
                    ),
                ),
            ],
            bases=("db_users.students",),
        ),
    ]
