from . import help
from . import start
from . import course_handler
from . import backendgroup
from . import kompyuter_savod
from . import english
from . import frontend
from . import mobililova
from . import grafikdizayn
from . import robototexnika
from . import uchddizayn
from . import smm
from . import vediomontaj
from . import posts